import Head from 'next/head'
import Image from 'next/image'
import { Inter } from "next/font/google";
import styles from "myweb/styles/Home.module.css";
import Link from "next/link";
import Navbar from "../../Components/Navbar/Navbar";
import Project from "../../Components/project/project";
import Education from "../../Components/education/Education";
import Social from "../../Components/social/Social";
import About from "../../Components/about/About";
import Skills from "../../Components/skills/Skills";
import Footer from "../../Components/footer/Footer";


export default function Home() {
  return (
    <>
      <Head>
        <title>Brando&apos;s Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main} id="top">
        <Image
          src="/profil.jpg"
          alt="profil-pic"
          width={200}
          height={200}
          className="rounded-full"
          hidden
        />
        <div className="text-center  flex flex-col justify-around gap-2 text-myblack phone:mx-5">
          <h1 className="text-5xl font-oxygen ">Hi there!</h1>
          <h1 className="text-4xl font-oxygen ">I am Brando Margendy Bogar</h1>
          <h2 className="text-2xl mt-2">Front-end Developer</h2>
          <p className="text-xl">
            A Front-end Developer based in Manado, Indonesia
          </p>
        </div>
        <Social />

        <Link
          href="https://statichunt.com/demo/nextjs-hydrogen"
          target="_blank"
          hidden
        >
          Web referensi
        </Link>
      </main>
      <aside id="project" className="text-myblack">
        <Project />
      </aside>
      <aside id="about" className="text-myblack">
        <About />
      </aside>
      <aside id="resume" className="text-myblack">
        <Education />
      </aside>
      <aside className="text-myblack">
        <Skills />
      </aside>
      <aside className="text-myblack">
        <Footer />
      </aside>
    </>
  );
}

// ? harus lanjut cari tau apa itu tentang abouut ato m ganti ato hapus